### ISSUE TITLE
org-roam-node-find not finding file nodes whose title is a prefix of other node titles

### ISSUE THREAD

**Issue by Agizin** [org-roam/org-roam#1719]
### Description

`org-roam-node-find` fails to find existing file nodes when the title of that node is a prefix of another node's title.

#### Steps to Reproduce
1. Run `org-roam-node-find` to create a file node with title `Foo`
2. Run `org-roam-node-find` to create a file node with title `Food`
3. Run `org-roam-node-find` to open file `Foo` - this now returns an empty capture buffer.

#### Backtrace
No errors reported

#### Expected Results
File with title `Foo` should be found and opened with any notes that were saved in it.

#### Actual Results
Opening `Foo` returns an empty capture buffer. Opening the org-roam directory, I can see that the `Foo` node was created successfully. Additionally, I see `Foo` listed as an auto-complete target after running `org-roam-node-find`, but I'm still given an empty capture buffer when tab-completing to it.

I don't seem to be having this issue from nodes made from org headings, only files.

### Environment

- Emacs: GNU Emacs 27.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-06-04
- Framework: N/A
- Org: Org mode version 9.4.4 (release_9.4.4 @ /snap/emacs/current/usr/share/emacs/27.2/lisp/org/)
- Org-roam: 2.0.0

**Comment by jethrokuan** [comment]
Can you confirm that you're on latest commit? This might've been fixed in #1713 .

**Comment by Agizin** [comment]
Yeah, I'm running version 20210731.636 from MELPA which looks to be pointing at the latest commit. I've been seeing this behavior since I migrated from v1 about a week ago though.

**Comment by jethrokuan** [comment]
I followed the exact steps you provided and can't reproduce what you're seeing. Can you provide a minimal config where this happens (stripping out completion frameworks etc.), so we know the issue lies with Org-roam.

**Comment by emacs18** [comment]
I added the following lines to my top level org file.

    * Foo
    :PROPERTIES:
    :ID:       ID_:20210801T082225.605617
    :END:
    
    * Food
    :PROPERTIES:
    :ID:       ID_:20210801T082237.100250
    :END:

`org-roam-node-find` provided completions for both "Foo" and "Food". Selecting
either placed the cursor in the appropriate place, i.e., headlines for "Foo" or "Food".

**Comment by Agizin** [comment]
@emacs18 I'm seeing the same behavior as you describe on my end. It's only file nodes that present an issue for me, I haven't had any issues with opening to org headings using `org-roam-node-find`.

@jethrokuan I've just tested on a minimal emacs config and a fresh org-roam directory using the steps above - still seeing the same issue. My full minimal `init.el` is below:

```
(setq custom-file (concat user-emacs-directory "custom.el"))
(when (file-exists-p custom-file)
  (load custom-file))

(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile (require 'use-package))

(require 'org)

(use-package org-roam
      :ensure t
      :custom
      (org-roam-directory (file-truename "~/org-roam-test/"))
      :bind (("C-c n l" . org-roam-buffer-toggle)
             ("C-c n f" . org-roam-node-find)
             ("C-c n g" . org-roam-graph)
             ("C-c n i" . org-roam-node-insert)
             ("C-c n c" . org-roam-capture)
             ;; Dailies
             ("C-c n j" . org-roam-dailies-capture-today))
      :config
      (org-roam-setup)
      ;; If using org-roam-protocol
      (require 'org-roam-protocol))
```

**Comment by emacs18** [comment]
I can see the reported problem only if I use vanilla emacs completions.   If an alternate completions such as `helm` is used, then I don't see the problem.  The problem can be seen  either with file nodes defined via `#+title` or with headline nodes.

The problem seems to be that you have to hit `TAB` key at the end of name completion in order for the name to be found.  If `TAB` is not hit, then a new node is created.  For example if I type "Food" followed by `TAB` then `RETURN` to complete the name, then existing node named "Food" is found.  However if I type "Food" followed by `RETURN` without having typed `TAB`, then a new node is created.

It is strange that hitting `TAB` to complete a name completion seems to insert bunch of white spaces followed by CR character.  Also successful identification of an existing node name seems to require this addition whitespaces inserted by `TAB` is even more weird!  This is why there is no way to find existing name "Foo" when "Food" node also exist.  During completion, hitting `TAB` after typing "Foo" does not insert whitespaces.  Rather only the completion pops up to show all names with "Foo" prefix.  If `RETURN` is hit, then "Foo" item is selected without having inserted all those whitespaces!  That is why you cannot select existing node named "Foo".

**Comment by emacs18** [comment]
This name completion problem is seen on both emacs 27 and emacs 28 which I built on ubuntu 20.04.

**Comment by emacs18** [comment]
I stated before that using an alternate completions resolves the problem.  To be specific, adding the following line to the config file above resolves the problem:
```
(use-package helm :ensure t :config (helm-mode))
```

**Comment by Agizin** [comment]
Ah, I see. I did think the extra whitespace after tab-completing was unusual, but didn't connect that to the problem I was having. I can confirm that adding helm to the config resolves the issue. Thank you for the help!
